public enum Muscle: String {
  case wristFlexors                  = "Wrist Flexors"
  case wristExtensors                = "Wrist Extensors"
  case tricepsBrachii                = "Triceps Brachii"
  case trapeziusUpperFibers          = "Trapezius Upper Fibers"
  case trapeziusMiddleFibers         = "Trapezius Middle Fibers"
  case trapeziusLowerFibers          = "Trapezius Lower Fibers"
  case trapezius                     = "Trapezius"
  case transverseAbdominus           = "Transverse Abdominus"
  case tibialisAnterior              = "Tibialis Anterior"
  case teresMinor                    = "Teres Minor"
  case teresMajor                    = "Teres Major"
  case tensorFasciaeLatae            = "Tensor Fasciae Latae"
  case subscapularis                 = "Subscapularis"
  case sternocleidomastoid           = "Sternocleidomastoid"
  case splenius                      = "Splenius"
  case soleus                        = "Soleus"
  case serratusAnterior              = "Serratus Anterior"
  case sartorius                     = "Sartorius"
  case rhomboids                     = "Rhomboids"
  case rectusAbdominis               = "Rectus Abdominis"
  case quadriceps                    = "Quadriceps"
  case pectoralisMajorSternalHead    = "Pectoralis Major Sternal Head"
  case pectoralisMajorClavicularHead = "Pectoralis Major Clavicular Head"
  case pectineous                    = "Pectineous"
  case obliques                      = "Obliques"
  case levatorScapulae               = "Levator Scapulae"
  case latissimusDorsi               = "Latissimus Dorsi"
  case infraspinatus                 = "Infraspinatus"
  case iliopsoas                     = "Iliopsoas"
  case hamstrings                    = "Hamstrings"
  case gracilis                      = "Gracilis"
  case gluteusMinimus                = "Gluteus Minimus"
  case gluteusMedius                 = "Gluteus Medius"
  case gluteusMaximus                = "Gluteus Maximus"
  case gastrocnemius                 = "Gastrocnemius"
  case erectorSpinae                 = "Erector Spinae"
  case deltoidPosterior              = "Deltoid Posterior"
  case deltoidLateral                = "Deltoid Lateral"
  case deltoidAnterior               = "Deltoid Anterior"
  case brachioradialis               = "Brachioradialis"
  case brachialis                    = "Brachialis"
  case bicepsBrachii                 = "Biceps Brachii"
  case adductorMagnus                = "Adductor Magnus"
  case adductorLongus                = "Adductor Longus"
  case adductorBrevis                = "Adductor Brevis"
}

extension Muscle: Codable {}
extension Muscle: Equatable {}
extension Muscle: Hashable {}
extension Muscle: CaseIterable {}
extension Muscle: Identifiable { public var id: String { rawValue } }
extension Muscle: CustomStringConvertible { public var description: String { rawValue } }
